export const planFeatures = [
  {
    key: 'free',
    name: 'Бесплатный',
    monthly: 0,
    yearlyMonthly: 0,
    description: '7 дней доступа без привязки карты. Полный\n функционал тарифа «Бизнес».',
    popular: false,
    paidUntil: null,
  },
  {
    key: 'business',
    name: 'Бизнес',
    monthly: 6990,
    yearlyMonthly: Math.round(6990 * 0.8),
    description: 'Безлимит: карты, сотрудники, уведомления,\n сертификаты.',
    popular: true,
    paidUntil: '2025-09-11',
  },
  {
    key: 'network',
    name: 'Сеть',
    monthly: 3990,
    yearlyMonthly: Math.round(3990 * 0.8),
    description: 'Тот же функционал, гибкая стоимость от 3\n точек',
    note: 'от 3 990₽ / мес / точка',
    popular: false,
    paidUntil: null,
  },
];
