export const planFeatures = [
  {
    key: 'free',
    name: 'Бесплатный',
    monthly: 0,
    yearlyMonthly: 0,
    description: '7 дней доступа без привязки карты. Полный\nфункционал тарифа «Бизнес».',
    popular: false,
    paidUntil: null,
    branchesLimit: 1,
    branchesText: 'До 1 торговой точки',
  },
  {
    key: 'business',
    name: 'Бизнес',
    monthly: 6990,
    yearlyMonthly: Math.round(6990 * 0.8),
    description: 'Безлимит: карты, сотрудники, уведомления,\nсертификаты.',
    popular: true,
    paidUntil: '2025-09-11',
    branchesLimit: null,
    branchesText: 'Безлимит торговых точек',
  },
  {
    key: 'network',
    name: 'Сеть',
    monthly: 3990,
    yearlyMonthly: Math.round(3990 * 0.8),
    description: 'Тот же функционал, гибкая стоимость от 3\nточек',
    note: 'от 3 990₽ / мес / точка',
    popular: false,
    paidUntil: null,
    branchesLimit: null,
    branchesText: 'Безлимит торговых точек (от 3 точек)',
  },
];
