export const defaultCardTemplate = {
  id: 3333,
  status: 'stamp',
  name: 'Накопительная карта',
  isActive: false,
  urlCopy: 'http://147.45.229.94:3000/customer/card/1234560',
  qrImg: '/qr-code.svg',
  frameUrl: '/phone.svg',
  balanceMoney: 1800,
  stamps: 1,
  cardImg: '',
  untilNextReward: 2,
  currentLevel: '',
  balance: 500,
  title: 'Сертификат',
  expirationDate: '00.00.0000',
  firstVisitDiscount: '10',
  visitsCount: 8,
  certificateName: 'Ivan',
  cardLevel: 'Золотой',
  discountStatus: 'Бронзовый',
  discountPercent: 1,
  credits: 1000,
  cashbackStatus: 'Бронзовый',
  cashbackPercent: 1,
  settings: {
    rewardProgram: 'stamps',
    cardLimit: 'cardUnlimit',
    stampLimit: 'stampUnlimit',
    pointsLimit: 'pointsUnlimit',
    card: {},
    stamp: {},
    spendingAmount: 500,
    spendingStamps: 1,
    visitStamps: 1,
    limitVisitPerDay: false,
    locations: [],
    language: 'ru',
    phoneMask: 'Russia',
    redemptionRule: 'multiple', // multiple | single
  },
  score: 10,
  subscribersCount: 0,
  pushNotification: {
    message: '',
    scheduledDate: '',
    locations: [
      {
        name: 'Москва, ул. Арбат, 10',
        coords: [55.7522, 37.6156],
        active: true,
        message: 'Вы рядом с нашим магазином на Арбате! Зайдите за подарком 🎁',
      },
      {
        name: 'Санкт-Петербург, Невский проспект',
        coords: [59.9343, 30.3351],
        active: true,
        message: 'Скидка 15% для гостей у Невского! Ждём вас 👋',
      },
    ],
  },
  design: {
    logo: null,
    icon: null,
    stampBackground: null,
    background: null,
    stampsQuantity: 10,
    activeStamp: 'Star',
    inactiveStamp: 'Star',
    activeStampImage: null,
    inactiveStampImage: null,
    colors: {
      cardBackground: '#FFFFFF',
      stampBackgroundColor: '#F6F6F6',
      textColor: '#1F1E1F',
      stampColor: '#ffffff',
      activeStampColor: '#1F1E1F',
      borderColor: '#1F1E1F',
      inactiveStampColor: '#1F1E1F',
    },
  },
  issueFormFields: [
    { type: 'name', name: 'Имя', required: false, unique: false },
    { type: 'surname', name: 'Фамилия', required: false, unique: false },
    { type: 'phone', name: 'Телефон', required: false, unique: true },
    { type: 'email', name: 'Email', required: false, unique: true },
    { type: 'birthday', name: 'Дата рождения', required: false, unique: false },
  ],
  statusFields: [
    { name: 'Бронзовый', cost: '0', percent: '1' },
    { name: 'Серебряный', cost: '5000', percent: '3' },
    { name: 'Золотой', cost: '10000', percent: '5' },
  ],
  utmLinks: [],
  fieldsName: [],
  requirePurchaseAmountOnAccrual: false,
  initialPointsOnIssue: '',
  policySettings: {
    policyEnabled: true,
    consentEnabled: false,
    policyText: 'Я согласен с тем, что мои личные данные могут использоваться...',
    fullPolicyText:
      'Я согласен с тем, что мои личные данные могут использоваться (полный текст)...',
  },
  issueLimit: '',
  infoFields: {
    description: 'Получайте бонусные баллы за каждую покупку',
    howToGetStamp: 'Сделайте покупку, чтобы получить штамп',
    companyName: 'Название компании',
    rewardDescription: 'Описание награды',
    stampMessage: 'Всего {#} осталось до получения награды!',
    claimRewardMessage: 'Ваша награда ждет вас! Приходите за получением подарка',
    multiRewards: [],
    autoRedeem: false,
    referralProgramActive: true,
    referralMoment: 'visit',
    referrerStampsQuantity: 1,
    referralStampsQuantity: 1,
  },
};
